name: Build and Test

on: push

env:
  # no spam
  DOTNET_NOLOGO: true

  # notracking
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  build:
    name: build with .NET Core
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow    
    
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
            
    - name: Create version tag
      run: |
        git tag ${{ steps.gitversion.outputs.semVer }}
        git push
            
    - run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "Major: ${{ steps.gitversion.outputs.major }}"
    - name: Install dependencies
      run: dotnet restore './src/HKDFrfc5869.sln'
    - name: Build
      run: dotnet build './src/HKDFrfc5869.sln' --configuration Release --no-restore

  test:
    name: testing with .NET Core
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Test
      run: dotnet test './src/HKDFrfc5869.sln' --no-restore --verbosity normal
